id: undead_slayer
trigger: ON_ATTACK

display-name: "<red>Undead Slayer {level}"
lore:
  - "<gray>Deals <red>{damage}% <gray>more damage"
  - "<gray>to undead mobs"

applicable-items:
  - DIAMOND_SWORD
  - NETHERITE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - STONE_SWORD
  - WOODEN_SWORD

conditions:
  mob-type:
    - ZOMBIE
    - SKELETON
    - WITHER_SKELETON
    - ZOMBIFIED_PIGLIN
    - DROWNED
    - HUSK
    - STRAY
    - PHANTOM

levels:

  1:
    chance: 100
    cooldown: 1500
    effects:
      - type: DAMAGE_BOOST
        multiplier: 1.1
    placeholder:
      damage: 10
  2:
    chance: 100
    cooldown: 1400
    effects:
      - type: DAMAGE_BOOST
        multiplier: 1.2
    placeholder:
      damage: 20
  3:
    chance: 100
    cooldown: 1300
    effects:
      - type: DAMAGE_BOOST
        multiplier: 3
    placeholder:
      damage: 300